### ISSUE TITLE
Can't click on "Yes" on opening disclaimer

### ISSUE THREAD

**Issue by formicsapien** [maxvollmer/Half-Life-VR#3]
I'm not entirely sure I'm building this correctly.  I copied and pasted everything in any "Debug" folder after building every solution in VS.  

Anyways, I got it to launch, but when I try to open the game it has a little window that asks if I understand dev has no liability.  Whenever I click anywhere the game minimizes, and I cannot advance past the box.

**Comment by maxvollmer** [comment]
Are you running in fullscreen? I've never tried this in fullscreen. Maybe the modal dialog and fullscreen mode don't get a long. Anyways, it's a simple Win32 API MessageBox. Just comment it out if nothing else helps.

**Comment by formicsapien** [comment]
Yup, that was it.  THANKS!  (I have another problem, it says "failed to load custom opengl32.dll. Make sure you launch the game through HLVRLauncher.exe, not the Steam menu."  I am using the HLVRLauncher, and it's still does this.)

**Comment by maxvollmer** [comment]
The launcher is supposed to copy the opengl32.dll into the Half-Life folder and add an entry to the ACL so Half-Life doesn't delete it. Try running it as admin if it doesn't work. Otherwise maybe your version of Windows is incompatible with the code in the launcher, I use Windows 10 and the launcher in its current version is just something I quickly hacked together so I can test the mod on my system. I REALLY DO NOT RECOMMEND THIS, but you could also just manually place the opengl32.dll into your Half-Life folder and then manually use the security tab of the Half-Life folder and add a deny entry for user Everyone to "delete files". Either way, before I release this officially I really cannot help you further, I am sorry. You have the source code, I am pretty sure you can figure this out!

**Comment by NTripleOne** [comment]
Just an FYI, please be extremely careful when using custom replacement DLLs, forgetting to remove them and trying to play half-life online could result in getting VAC banned across all goldsrc games at worst, and getting VAC kicked at best.

**Comment by maxvollmer** [comment]
This is exactly why I don't recommend anyone do this.

**Comment by formicsapien** [comment]
@maxvollmer I think you covered your bases well enough with the disclaimer.  Honestly, taking care to disconnect my internet every time I launch is **_WELL_** worth it to be able to play HL in VR!

**Comment by maxvollmer** [comment]
This no longer applies, the game doesn't display that message box anymore.
